# Generated by Django 5.0.4 on 2024-05-05 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Attribute', models.CharField(max_length=100, null=True)),
                ('Task', models.CharField(max_length=100, null=True)),
                ('Duration', models.PositiveIntegerField(null=True)),
                ('Predecessors', models.CharField(max_length=100, null=True)),
                ('EarliestST', models.PositiveIntegerField(null=True)),
                ('LatestST', models.PositiveIntegerField(null=True)),
                ('Slack', models.PositiveIntegerField(null=True)),
                ('RequiredRT', models.CharField(max_length=100, null=True)),
                ('EstimatedEf', models.PositiveIntegerField(null=True)),
            ],
        ),
    ]
