# Generated by Django 5.0.4 on 2024-06-04 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='Progress',
            field=models.CharField(choices=[('Done', 'Done'), ('In progress', 'In progress'), ('Not started', 'Not started')], default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='Staffid',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
