# Generated by Django 5.0.4 on 2024-06-04 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0002_task_progress_task_staffid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='Progress',
            field=models.CharField(choices=[('Done', 'Done'), ('In progress', 'In progress'), ('Not started', 'Not started')], default='Not Started', max_length=50),
        ),
    ]
