# Generated by Django 5.0.4 on 2024-06-11 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0003_alter_task_progress'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='Slack',
            new_name='ffloat',
        ),
        migrations.AddField(
            model_name='task',
            name='tfloat',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
